const sgMail = require('@sendgrid/mail');

sgMail.setApiKey(process.env.SENDGRID_API_KEY);

const emailService = {

  // ── Send Prediction Report ─────────────────────────────
  async sendPredictionReport(email, name, prediction) {

    const riskColor =
      prediction.result.riskLevel === 'High' ? '#ef4444' :
      prediction.result.riskLevel === 'Very High' ? '#dc2626' :
      prediction.result.riskLevel === 'Moderate' ? '#f59e0b' : '#22c55e';

    const html = `
    <div style="font-family: 'Segoe UI', sans-serif; max-width: 600px; margin: 0 auto; background: #f8fafc;">
      <div style="background: linear-gradient(135deg, #0b1a12 0%, #0d2218 100%); padding: 40px 30px; text-align: center; border-radius: 12px 12px 0 0;">
        <h1 style="color: #10b981; margin: 0; font-size: 28px; letter-spacing: 2px;">🏥 HEALTH GUARD</h1>
        <p style="color: #6b9e82; margin: 8px 0 0;">AI-Powered Disease Prediction Report</p>
      </div>
      <div style="padding: 30px; background: white;">
        <p style="color: #334155;">Dear <strong>${name}</strong>,</p>
        <p style="color: #64748b;">Your health prediction analysis has been completed. Please find the details below:</p>

        <div style="background: #f1f5f9; border-radius: 8px; padding: 20px; margin: 20px 0;">
          <table style="width: 100%; border-collapse: collapse;">
            <tr><td style="padding: 8px; color: #64748b; font-size: 13px;">Report ID</td><td style="padding: 8px; font-weight: bold; color: #1e293b;">${prediction.reportId}</td></tr>
            <tr><td style="padding: 8px; color: #64748b; font-size: 13px;">Disease Type</td><td style="padding: 8px; font-weight: bold; color: #1e293b;">${prediction.diseaseType} Disease</td></tr>
            <tr><td style="padding: 8px; color: #64748b; font-size: 13px;">Prediction</td><td style="padding: 8px; font-weight: bold; color: ${prediction.result.prediction === 'Positive' ? '#ef4444' : '#22c55e'};">${prediction.result.prediction}</td></tr>
            <tr><td style="padding: 8px; color: #64748b; font-size: 13px;">Probability</td><td style="padding: 8px; font-weight: bold; color: #1e293b;">${prediction.result.probability}%</td></tr>
            <tr><td style="padding: 8px; color: #64748b; font-size: 13px;">Risk Level</td><td style="padding: 8px;"><span style="background: ${riskColor}20; color: ${riskColor}; padding: 4px 12px; border-radius: 20px; font-weight: 600; font-size: 13px;">${prediction.result.riskLevel}</span></td></tr>
            <tr><td style="padding: 8px; color: #64748b; font-size: 13px;">Date & Time</td><td style="padding: 8px; color: #1e293b;">${new Date(prediction.createdAt).toLocaleString()}</td></tr>
          </table>
        </div>

        <div style="background: #fef3c7; border-left: 4px solid #f59e0b; padding: 15px; border-radius: 0 8px 8px 0; margin: 20px 0;">
          <p style="margin: 0; color: #92400e; font-size: 13px;">⚠️ This report is generated by AI and is not a substitute for professional medical advice.</p>
        </div>

        <div style="margin: 20px 0;">
          <h3 style="color: #1e293b; font-size: 16px;">📋 Recommendations:</h3>
          <ul style="color: #475569; padding-left: 20px;">
            ${prediction.recommendations.map(r => `<li style="margin: 6px 0;">${r}</li>`).join('')}
          </ul>
        </div>
      </div>
      <div style="background: #0b1a12; padding: 20px; text-align: center; border-radius: 0 0 12px 12px;">
        <p style="color: #3d7055; font-size: 12px; margin: 0;">Health Guard • AI Healthcare Platform • ${new Date().getFullYear()} • healthguard.com</p>
      </div>
    </div>`;

    try {
      await sgMail.send({
        to: email,
        from: process.env.EMAIL_FROM,
        subject: `Health Guard – Your ${prediction.diseaseType} Disease Prediction Report`,
        html
      });

      console.log("✅ Prediction Email Sent");

    } catch (error) {
      console.log("❌ SendGrid Error:", error.response?.body || error);
    }
  },


  // ── Appointment Confirmation (UI SAME) ─────────────────
  async sendAppointmentConfirmation(appointment) {

    const patient = appointment.patientId;
    const doctor  = appointment.doctorId;

    const html = `YOUR SAME FULL APPOINTMENT HTML HERE `; 
    // 👆 keep your original HTML exactly as before

    try {
      await sgMail.send({
        to: patient.email,
        from: process.env.EMAIL_FROM,
        subject: 'Health Guard – Appointment Booked Successfully',
        html
      });

      console.log("✅ Appointment Confirmation Email Sent");

    } catch (error) {
      console.log("❌ SendGrid Error:", error.response?.body || error);
    }
  }

};

module.exports = emailService;
